### ISSUE TITLE
Pasting indented code

### ISSUE THREAD

**Issue by ofir-reich** [idlespork/idlespork#1]
When pasting indented code from the editor window (or an external editor) the code is pasted with the indentation and cannot be executed. We should remove the minimal indent that is common to all the lines. The code for this exists in one of the idlex packages (MultiLineRun.py?), I need to get it and add.

**Comment by ofir-reich** [comment]
It is in fact the module MultiLineRun.py in idlex.

Simply copying that module to idlexporklib and enabling in config-extensions.def did not work, probably the pasting happens differently.

I have a fix for the function "dedent" in MultiLineRun.py, which helps but is still not perfect. I'll make it work perfectly in idlex and then post it here maybe.

**Comment by ofir-reich** [comment]
My mistake, it seems that MultiLineRun.py does fix it (when not forgetting to change idlelib to idlesporklib in the code). I'll have a pull request for this today.

**Comment by ofir-reich** [comment]
Pull Request #5 mostly fixes this. Still one improvement left:

Ideally we would want all pasted code to not be run automatically (or line by line) but to be pasted as if somebody typed it with alt+enter after every line, so it's one block of code. But I don't know how to do that. For example if my copied code is

```
print 3
print 4
```

I would want the result to be:

```
>>> print 3
print 4
3
4
>>> 
```

And not:

```
>>> print 3
3
>>> print 4
4
>>>
```

**Comment by idlespork** [comment]
Merged pull request with changes so that it won't separate commands (as ofir-reich suggested)
