### ISSUE TITLE
BUG: links don't appear, braces instead

### ISSUE THREAD

**Issue by ofir-reich** [idlespork/idlespork#18]
Recently installed the new idlespork and enabled some extensions.
Now suddenly links don't appear. I tried playing around with the configurations. Didn't work (though I didn't exhaust the options). See config file attached
[config-extensions.cfg](https://github.com/idlespork/idlespork/files/1977691/config-extensions.cfg.txt)

```
^0^[00:00.00] >>> walk

Traceback (most recent call last):
  File "{{{IDLESPORK_LINK:1}}}", line 1, in <interactive>
    walk
NameError: name 'walk' is not defined
^0^[00:00.15] >>> 
^0^[00:00.05] >>> my_var_name = 17
^0^[00:00.06] >>> my_vr_name

Traceback (most recent call last):
  File "{{{IDLESPORK_LINK:2}}}", line 1, in <interactive>
    my_vr_name
NameError: name 'my_vr_name' is not defined

Did you mean {{{IDLESPORK_LINK:3}}}?
^0^[00:00.13] >>> 
```

**Comment by ofir-reich** [comment]
@drorspei @goldberglior - any idea what's up? I think this is from the recent update, but I thought it was working fine with the same files before I reinstalled from pip. Do you have the same issue? Is it that I messed up my config file somehow?

**Comment by goldberglior** [comment]
Try to enable BetterOutput, this should solve it. I am not sure why the links are not recognized otherwise, I'll try to check it soon.
@drorspei - Do you know what happened here?

**Comment by drorspei** [comment]
Crap.
No, haven't seen this, neither anyone at my company (we have 9 people actively using idlespork). 
Did enabling BetterOutput work?

**Comment by ofir-reich** [comment]
Yep, enabling BetterOutput and opening a new shell solved it. For some
reason it didn't update on the existing shell.

Thanks!

**Comment by goldberglior** [comment]
BetterOutput is the extension responsible on handling the links, so this is expected.
